backend:
  name: git-gateway
  branch: master

media_library:
  name: uploadcare
  config:
    publicKey: 8c2097816b0c71e124aa

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index"}
          - label: "Featured Project"
            name: "featuredProject"
            widget: "relation"
            collection: "projects"
            searchFields: ["title"]
            valueField: "title"
            displayField: ["title"]
          - {label: "Facebook Link", name: "facebook", widget: "string"}
          - {label: "Instagram Link", name: "instagram", widget: "string"}
          - {label: "Email Link", name: "email", widget: "string"}
          - {label: "Keywords (comma separated)", name: "keywords", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Image"
            name: "image"
            widget: "image"
            options:
              media_library:
                config:
                  multiple: false
                  previewStep: true
  - name: "projects"
    label: "Project"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sort Key", name: "sortKey", widget: "number", default: 0}
      - label: "Images"
        name: "images"
        widget: "image"
        options:
          media_library:
            config:
              multiple: true
              previewStep: true
